name: Build Docker image

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: get jq tag and export as an output
        id: jq-tag
        run: echo "tag=$(cat '.jq-tag')" >> $GITHUB_OUTPUT
      - name: Extract metadata (tags, labels) for ghcr
        id: meta-ghcr
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/whi-tw/jq-docker
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=raw,value=${{ steps.jq-tag.outputs.tag }},enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
          labels: |
            org.opencontainers.image.url=https://github.com/whi-tw/jq-docker
            org.opencontainers.image.source=https://github.com/whi-tw/jq-docker
            org.opencontainers.image.documentation=https://github.com/whi-tw/jq-docker
            org.opencontainers.image.title=jq-docker
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta-ghcr.outputs.tags }}
          labels: ${{ steps.meta-ghcr.outputs.labels }}
          build-args:
            - JQ_TAG=${{ steps.jq-tag.outputs.tag }}
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
